### ISSUE TITLE
fizi impute 

### ISSUE THREAD

**Issue by ooozcl** [bogdanlab/fizi#4]
Hello,
when I run fizi impute cleaned.gwas.sumstats.gz 19-5.QC --chr 19 --out imputed.cleaned.gwas.chr1.sumstat,I get error :Error：unsupported operand type(s) for +: 'float' and 'str'

**Comment by quattro** [comment]
Hi @ooozcl , please try the latest version in the repository.

**Comment by quattro** [comment]
Updated pypi, conda-forge, and installation instructions to point to latest.
