### ISSUE TITLE
Cannot convert non-finite values (NA or inf) to integer

### ISSUE THREAD

**Issue by Nobuyuki-Enzan** [bogdanlab/fizi#7]
Hi, fizi team

I am trying to impute my summary statistics, and ran into the error saying "Cannot convert non-finite values (NA or inf) to integer".
I know that this error have been already discussed in "Running sumstat imputation #5",
but none of the workaround did not work for me.

Specifically, I did
1. imputed summary statistics with fizi
2. loaded my sumstats in R and double check that there are no NA/NaN/Inf values.
3. set min-prop as 0.1
4. removed variants using plink --max-maf 0.49
 Still, I have the same error.

Here is the full log.
[LOG.txt](https://github.com/bogdanlab/fizi/files/9707182/LOG.txt)

It is appreciated if you could tell me how to solve this error.
Best,
Nobuyuki

**Comment by quattro** [comment]
Hi @Nobuyuki-Enzan , can you verify that your pandas installation is up to date?

**Comment by Nobuyuki-Enzan** [comment]
Hi Nicholas,

Thank you for your quick response.
Yes, my pandas version is 1.5.0.
I created conda environment as follows.
```
mamba create -n pyfizi_env -c conda-forge pyfizi
```

**Comment by quattro** [comment]
Thanks. If you are allowed to share the sumstats (or at least those near the region w/ error), we can take a look to see what is going on.

**Comment by Nobuyuki-Enzan** [comment]
Hi Nick, 

Thank you for your help.
I noticed that my LD reference panel had variants with MAC = 0.
Excluding these variants works for me.

Now that I have no problem, I close this session.
